// <auto-generated />
namespace HipChatCentral.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AbstractApiKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AbstractApiKey));
        
        string IMigrationMetadata.Id
        {
            get { return "201304211759347_AbstractApiKey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
