// <auto-generated />
namespace HipChatCentral.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddRegistrationId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRegistrationId));
        
        string IMigrationMetadata.Id
        {
            get { return "201304191752254_AddRegistrationId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
